import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "@styles/mainbundle.scss";
import "@styles/stylesheet.css";
import "@styles/test.css";
// import AOSInit from "@common/AOSInit";
// import Header from "@common/Header";
// import Footer from "@common/Footer";
import ClientLayoutWrapper from "@common/ClientLayoutWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
      </body>
    </html>
  );
}
